accelerator: null
accumulate_grad_batches: 1
amp_backend: native
amp_level: O2
auto_lr_find: false
auto_scale_batch_size: false
auto_select_gpus: false
balance_sampling: 1
batch_size: 1
benchmark: false
cache_dir: null
cache_rate: null
check_val_every_n_epoch: 1
checkpoint_callback: true
class_weight: null
cls_loss: CE
connection: skip
dataset: invitro
default_root_dir: null
deterministic: false
devices: null
distributed_backend: null
fast_dev_run: false
flush_logs_every_n_steps: 100
fold: 0
gpus: null
gradient_clip_algorithm: norm
gradient_clip_val: 0.0
in_channels: 1
ipus: null
limit_predict_batches: 1.0
limit_test_batches: 1.0
limit_train_batches: 1.0
limit_val_batches: 1.0
log_dir: /mnt/Data/Cryo-ET/3D-UCaps/logs
log_every_n_steps: 50
log_gpu_memory: null
logger: true
lr_rate: 0.0001
margin_loss_weight: 0.1
max_epochs: null
max_steps: null
max_time: null
min_epochs: null
min_steps: null
model_name: ucaps
move_metrics_to_cpu: false
multiple_trainloader_mode: max_size_cycle
num_nodes: 1
num_processes: 1
num_samples: 32
num_sanity_val_steps: 2
num_workers: 4
out_channels: 3
overfit_batches: 0.0
overlap: 0.5
plugins: null
precision: 32
prepare_data_per_node: true
process_position: 0
profiler: null
progress_bar_refresh_rate: null
rec_loss_weight: 0.1
reload_dataloaders_every_epoch: false
reload_dataloaders_every_n_epochs: 0
replace_sampler_ddp: true
resume_from_checkpoint: null
root_dir: /mnt/Data/Cryo-ET/3D-UCaps/data/invitro
share_weight: 1
stochastic_weight_avg: false
sw_batch_size: 1
sync_batchnorm: false
terminate_on_nan: false
tpu_cores: null
track_grad_norm: -1
train_patch_size:
- 64
- 64
- 64
truncated_bptt_steps: null
use_class_weight: 0
val_check_interval: 1.0
val_frequency: 10
val_patch_size: 128
weight_decay: 1.0e-06
weights_save_path: null
weights_summary: top
