# -*- coding: utf-8 -*-
# Form implementation generated from reading ui file 'train.ui'
# Created by: PyQt5 UI code generator 5.13.2
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(660, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 631, 397))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.modelL = QtWidgets.QLabel(self.gridLayoutWidget)
        self.modelL.setObjectName("modelL")
        self.gridLayout_2.addWidget(self.modelL, 2, 0, 1, 1)
        self.lossL = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lossL.setObjectName("lossL")
        self.gridLayout_2.addWidget(self.lossL, 6, 0, 1, 1)
        self.targetPath = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.targetPath.setObjectName("targetPath")
        self.gridLayout_2.addWidget(self.targetPath, 1, 1, 1, 1)
        self.imagePathL = QtWidgets.QLabel(self.gridLayoutWidget)
        self.imagePathL.setObjectName("imagePathL")
        self.gridLayout_2.addWidget(self.imagePathL, 0, 0, 1, 1)
        self.LRL = QtWidgets.QLabel(self.gridLayoutWidget)
        self.LRL.setObjectName("LRL")
        self.gridLayout_2.addWidget(self.LRL, 3, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.LR = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.LR.setObjectName("LR")
        self.horizontalLayout.addWidget(self.LR)
        self.epochL = QtWidgets.QLabel(self.gridLayoutWidget)
        self.epochL.setObjectName("epochL")
        self.horizontalLayout.addWidget(self.epochL)
        self.epochs = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.epochs.setObjectName("epochs")
        self.horizontalLayout.addWidget(self.epochs)
        self.batchL = QtWidgets.QLabel(self.gridLayoutWidget)
        self.batchL.setObjectName("batchL")
        self.horizontalLayout.addWidget(self.batchL)
        self.batchsize = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.batchsize.setObjectName("batchsize")
        self.horizontalLayout.addWidget(self.batchsize)
        self.patchL = QtWidgets.QLabel(self.gridLayoutWidget)
        self.patchL.setObjectName("patchL")
        self.horizontalLayout.addWidget(self.patchL)
        self.patchsize = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.patchsize.setObjectName("patchsize")
        self.horizontalLayout.addWidget(self.patchsize)
        self.gridLayout_2.addLayout(self.horizontalLayout, 3, 1, 1, 1)
        self.imagePath = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.imagePath.setObjectName("imagePath")
        self.gridLayout_2.addWidget(self.imagePath, 0, 1, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.textEdit.setMaximumSize(QtCore.QSize(16777215, 150))
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_2.addWidget(self.textEdit, 8, 0, 1, 2)
        self.widthL = QtWidgets.QLabel(self.gridLayoutWidget)
        self.widthL.setObjectName("widthL")
        self.gridLayout_2.addWidget(self.widthL, 5, 0, 1, 1)
        self.horizontalLayout9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout9.setObjectName("horizontalLayout9")
        self.width = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.width.setObjectName("Width")
        self.horizontalLayout9.addWidget(self.width)
        self.heightL = QtWidgets.QLabel(self.gridLayoutWidget)
        self.heightL.setObjectName("heightL")
        self.horizontalLayout9.addWidget(self.heightL)
        self.height = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.height.setObjectName("Height")
        self.horizontalLayout9.addWidget(self.height)
        self.depthL = QtWidgets.QLabel(self.gridLayoutWidget)
        self.depthL.setObjectName("depthL")
        self.horizontalLayout9.addWidget(self.depthL)
        self.depth = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.depth.setObjectName("depth")
        self.horizontalLayout9.addWidget(self.depth)
        self.classNumL = QtWidgets.QLabel(self.gridLayoutWidget)
        self.classNumL.setObjectName("classNumL")
        self.horizontalLayout9.addWidget(self.classNumL)
        self.classNum = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.classNum.setObjectName("classNum")
        self.horizontalLayout9.addWidget(self.classNum)
        self.gridLayout_2.addLayout(self.horizontalLayout9, 5, 1, 1, 1)
        self.trainBtn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.trainBtn.setObjectName("trainBtn")
        self.gridLayout_2.addWidget(self.trainBtn, 7, 0, 1, 2)
        self.targetPathL = QtWidgets.QLabel(self.gridLayoutWidget)
        self.targetPathL.setObjectName("targetPathL")
        self.gridLayout_2.addWidget(self.targetPathL, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 4, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 660, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.modelL.setText(_translate("MainWindow", "model:"))
        self.lossL.setText(_translate("MainWindow", "loss:"))
        self.imagePathL.setText(_translate("MainWindow", "image path:"))
        self.LRL.setText(_translate("MainWindow", "learning rate:"))
        self.LR.setText(_translate("MainWindow", "0.001"))
        self.epochL.setText(_translate("MainWindow", "epochs:"))
        self.epochs.setText(_translate("MainWindow", "100"))
        self.batchL.setText(_translate("MainWindow", "batch size:"))
        self.batchsize.setText(_translate("MainWindow", "20"))
        self.patchL.setText(_translate("MainWindow", "patch size:"))
        self.patchsize.setText(_translate("MainWindow", "64"))
        self.trainBtn.setText(_translate("MainWindow", "train"))
        self.targetPathL.setText(_translate("MainWindow", "target path:"))
        self.label.setText(_translate("MainWindow", "Optimizer:"))
        self.widthL.setText(_translate("MainWindow", "Width:"))
        self.heightL.setText(_translate("MainWindow", "Height:"))
        self.depthL.setText(_translate("MainWindow", "Depth:"))
        self.classNumL.setText(_translate("MainWindow", "#Class:"))
        self.width.setText(_translate("MainWindow", "512"))
        self.height.setText(_translate("MainWindow", "512"))
        self.depth.setText(_translate("MainWindow", "512"))
        self.classNum.setText(_translate("MainWindow", "2"))

